platform:
  - x64

cache:
  # - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%LOCALAPPDATA%\electron-builder\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 18 x64
  - git reset --hard HEAD
  - npm install npm -g
  - node --version
  - npm --version
  - npm ci

build_script:
  - npm run build:full
  - .\node_modules\.bin\gulp build_plugins

artifacts:
  - path: dist\*.exe
    name: installer
  - path: dist\*.7z
    name: Archive
  - path: dist\*.7z
    name: Archive

branches:
  except:
    - /^v\d+\.\d+\.\d+.*/
