variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  THIS_MONTH: $[format('{0:yyyyMM}', pipeline.startTime)]

trigger:
  tags:
    include:
      - '*'
  branches:
    exclude:
      - '*'

pr: none

jobs:
- job: Linux
  strategy:
    matrix:
      full:
        buildType: full
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install --no-install-recommends -y libopenjp2-tools rpm libarchive-tools snapcraft
    displayName: 'Linux system dependencies'
  - template: shared-steps.yml

- job: macOS
  strategy:
    matrix:
      full:
        buildType: full
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: shared-steps.yml

- job: Windows
  strategy:
    matrix:
      full:
        buildType: full
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: shared-steps.yml
