variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm
  THIS_MONTH: $[format('{0:yyyyMM}', pipeline.startTime)]

jobs:
- job: Linux
  strategy:
    matrix:
      x64:
        buildType: x64
      arm64:
        buildType: arm64
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      sudo apt-get update
      sudo apt-get install --no-install-recommends -y libopenjp2-tools rpm libarchive-tools snapcraft
    displayName: 'Linux system dependencies'
  - template: shared-steps.yml

- job: macOS
  strategy:
    matrix:
      x64:
        buildType: x64
      arm64:
        buildType: arm64
  pool:
    vmImage: 'macOS-latest'
  steps:
  - template: shared-steps.yml

- job: Windows
  strategy:
    matrix:
      x64:
        buildType: x64
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: shared-steps.yml
